### ISSUE TITLE
Update the checklist card header when a checklist is modified

### ISSUE THREAD

**Issue by rrickgauer** [rrickgauer/Checklists#49]
- [x] item counts
   - [x] update when an item is added/deleted
   - [x] update when an item is marked complete/incomplete
 - [x] description
   - [x] update when a checklist's description is changed
 - ~~date modified~~
   - ~~update when an item is added/removed/changed/marked complete or incomplete~~

Probably going to have to split up the function that creates the checklist card header.

Then when an action is made to a checklist, I can call the data from the server and update the display
